[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxx"
client_id = "396115407622-t3pso5ibfpbn8nu8vqhp4645p02tnq41.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"  # fmt: skip


